from werkzeug.security import generate_password_hash

from database import get_connection, init_db

COURSES = ["Donnerstag 20:00 Uhr", "Sonntag 18:00 Uhr"]

DANCES = [
    "Langsamer Walzer",
    "Tango",
    "Wiener Walzer",
    "Slowfox",
    "Quickstep",
    "Cha Cha Cha",
    "Rumba",
    "Samba",
    "Jive",
    "Paso Doble",
    "Discofox",
]

DEFAULT_USERS = [
    {"username": "admin", "password": "admin123", "role": "admin", "course": "Donnerstag 20:00 Uhr"},
    {"username": "user", "password": "user123", "role": "teilnehmer", "course": "Donnerstag 20:00 Uhr"},
]

SAMPLE_FIGURES = {}

_REMOVED_SAMPLE_FIGURES = {
    "Langsamer Walzer": [
        (
            "Natural Turn",
            "Klassische Rechtsdrehung über zwei Takte.",
            "Anfänger",
            None,
            "Vorwärts, Seitwärts, Schließen",
            "6",
            "F: Rechts, M: Links",
            "1/4 rechts",
        ),
        (
            "Reverse Turn",
            "Gegenstück zur Naturdrehung nach links.",
            "Anfänger",
            None,
            "Vorwärts, Seitwärts, Schließen",
            "6",
            "F: Links, M: Rechts",
            "1/4 links",
        ),
        (
            "Whisk",
            "Eleganter Übergang mit Kreuzschritt.",
            "Fortgeschritten",
            None,
            "Seitenwechsel, Kreuzschritt, Schließen",
            "6",
            "F: Rechts, M: Links",
            "1/4 rechts",
        ),
        (
            "Closed Change",
            "Grundlegender Walzerschritt in geschlossener Haltung.",
            "Anfänger",
            None,
            "Vorwärts, Seite, Schließen",
            "6",
            "F: Rechts, M: Links",
            "keine",
        ),
        (
            "Open Reverse",
            "Rechtsdrehung aus offener Haltung mit erweitertem Raum.",
            "Fortgeschritten",
            None,
            "Seiten, Vorwärts, Schließen",
            "6",
            "F: Rechts, M: Links",
            "1/4 rechts",
        ),
    ],
    "Tango": [
        (
            "Open Reverse Turn Lady Outside",
            "Linksdrehung, bei der die Dame in CBMP außen vorbeigeführt wird.",
            "Anfänger",
            None,
            "LF vor in CBMP, RF Seite, LF zurück in CBMP, RF zurück, LF Seite und etwas vor, RF vor in CBMP OP",
            "Q Q S Q Q S",
            "H, BH, BH, BH, IE of F, H",
            "Knapp 3/4 nach links",
            "Walk auf RF; jedes Closed/Open Finish endend DC; Promenade Link endend DC; Brush Tap; Four Step Change; Outside Swivel to Left",
            "Walk auf LF; Progressive Side Step; Progressive Link; Four Step; Brush Tap; Outside Swivel to Right; Back Corte (Schritt 1 in CBMP); Rock auf LF. An einer Ecke: Four Step, Brush Tap, Four Step Change, Five Step",
        ),
        (
            "Progressive Side Step Reverse Turn",
            "Erweiterte Linksdrehung mit progressivem Seitenschritt, oft als Steigerung des Progressive Side Step.",
            "Fortgeschritten",
            None,
            "Zehn Schritte: u. a. LF vor in CBMP, RF Seite, LF schließt etwas, RF vor, LF Seitenschritt, RF zurück, LF zurück in CBMP, RF zurück, LF Seite, RF schließt an LF",
            "Q Q S S Q S Q Q Q S",
            "H, BH, BH, BH, H, IE of BH, IE of BH, BH, IE of F, Whole F",
            "3/4 nach links",
            "Walk auf RF; jedes Closed/Open Finish endend DC; Promenade Link endend DC; Brush Tap; Four Step; Four Step Change; Outside Swivel to Left",
            "Walk auf LF; Progressive Side Step; Progressive Link; Four Step; Brush Tap; Four Step Change; Five Step; Back Corte; Rock auf LF. In PP gedreht: jede Promenadenfigur. An einer Ecke: Four Step, Brush Tap, Four Step Change, Five Step",
        ),
        (
            "Natural Rock Turn",
            "Rechtsdrehende Wiegefigur mit Richtungswechsel und Gewichtsverlagerung über sieben Schritte.",
            "Anfänger",
            None,
            "RF vor, LF Seite und etwas zurück, RF zurück, LF zurück in CBMP, RF Seite und etwas vor, LF zurück, RF schließt an LF",
            "S Q Q S Q Q S",
            "H, IE of BH, IE of BH, IE of BH, BH, IE of F, Whole F",
            "1/4 rechts zwischen 1 und 3; keine Drehung auf 4; 1/4 links zwischen 5 und 6",
            "Walk auf LF; Progressive Side Step",
            "Walk auf LF; Progressive Side Step; Progressive Link; Four Step; Brush Tap; Four Step Change; Five Step; Back Corte; Rock auf LF. In PP gedreht: jede Promenadenfigur. An einer Ecke: Four Step, Brush Tap, Four Step Change, Five Step",
        ),
        (
            "Back Corte",
            "Klassischer Rückwärts-Corte aus der Linksdrehung mit markantem Schließschritt.",
            "Anfänger",
            None,
            "LF zurück (R-Seite führend), RF zurück in CBMP, LF Seite und etwas vor, RF schließt an LF",
            "S Q Q S",
            "IE of BH, BH, IE of F, Whole F",
            "1/4 links zwischen 2 und 3",
            "Rock auf RF in CBMP; Schritte 1–4 des Progressive Side Step Reverse Turn; Natural Twist Turn endend Rücken DC; jedes Closed/Open Finish an einer Ecke oder entlang der Raumseite",
            "Walk auf LF; Progressive Side Step; Progressive Link; Four Step; Brush Tap; Four Step Change; Five Step; Rock auf LF. In PP gedreht: jede Promenadenfigur. An einer Ecke: Rock auf LF, Four Step, Four Step Change, Five Step",
        ),
        (
            "Rock on Left Foot",
            "Kurze, kraftvolle Wiegefigur auf dem linken Fuß; oft als Übergang eingesetzt.",
            "Anfänger",
            None,
            "LF zurück (R-Seite führend), RF vor, LF zurück und etwas seitlich",
            "Q Q S",
            "IE of BH, H, IE of BH",
            "Keine Drehung",
            "Rock auf RF; Schritte 1–4 des Progressive Side Step Reverse Turn; Natural Twist Turn endend Rücken DC; jedes Closed/Open Finish an einer Ecke oder entlang der Raumseite",
            "Rock auf RF; jedes Closed oder Open Finish. Nach Open Finish werden Schritte 1 und 3 in CBMP getanzt",
        ),
        (
            "Rock on Right Foot",
            "Gegenstück zum Rock on Left Foot mit Gewicht und Führung über den rechten Fuß.",
            "Anfänger",
            None,
            "RF vor, LF zurück, RF vor und etwas seitlich",
            "Q Q S",
            "BH, H, BH",
            "Keine Drehung",
            "Rock auf LF; Schritte 1–3 des Open Reverse Turn Lady in Line; Schritte 1–7 des Progressive Side Step Reverse Turn; Schritte 1–4 des Natural Rock Turn",
            "Back Corte; Rock auf LF; Four Step endend DW",
        ),
        (
            "Natural Promenade Turn",
            "Rechtsdrehende Promenadenfigur aus der PP mit charakteristischem Pivot.",
            "Anfänger",
            None,
            "LF Seite in PP, RF vor und quer in CBMP und PP, LF Seite und etwas zurück (Pivot), RF vor (ohne Gewicht) in PP",
            "S Q Q S (1½ Takte)",
            "H, H, BHB, H of RF und IE of B LF",
            "3/4 rechts zwischen 2 und 4",
            "Progressive Link; Natural Twist Turn; Four Step; Fallaway Promenade; Oversway; Five Step; Reverse Five Step; Walk auf RF in PP gedreht; jedes Closed Finish in PP gedreht; Brush Tap in PP gedreht; Promenade Link endend in PP",
            "Closed Promenade; Open Promenade; Natural Promenade Turn to Natural Rock Turn; Natural Twist Turn; Promenade Link; Fallaway Promenade; Back Open Promenade; Chase",
        ),
        (
            "Natural Promenade Turn to Natural Rock Turn",
            "Verbindung einer Promenadendrehung mit dem Natural Rock Turn – zehn Schritte mit zwei vollständigen Rechtsdrehungsphasen.",
            "Fortgeschritten",
            None,
            "Zehn Schritte: Promenadenphase (LF Seite in PP, RF quer, LF Seite mit Pivot, RF vor in PP) und anschließend Rock-Turn-Phase",
            "S Q Q S Q Q Q S Q Q (3½ Takte)",
            "H, H, BHB, H, IE of BH, IE of BH, IE of BH, BH, IE of F, Whole F",
            "Eine komplette Rechtsdrehung zwischen 2 und 6; 1/4 links zwischen 8 und 9",
            "Progressive Link; Natural Twist Turn; Four Step; Fallaway Promenade; Oversway; Five Step; Reverse Five Step; Walk auf RF in PP gedreht; jedes Closed Finish in PP gedreht; Brush Tap in PP gedreht; Promenade Link endend in PP",
            "Walk auf LF; Progressive Side Step; Progressive Link; Four Step; Brush Tap; Four Step Change; Five Step; Back Corte; Rock auf LF. In PP gedreht: jede Promenadenfigur. An einer Ecke: Four Step, Brush Tap, Four Step Change, Five Step",
        ),
        (
            "Natural Twist Turn",
            "Rechtsdrehende Twist-Bewegung aus der PP mit gekreuzten Füßen und Lösung der Kreuzung.",
            "Fortgeschritten",
            None,
            "LF Seite in PP, RF vor und quer in CBMP und PP, LF Seite, RF kreuzt hinter LF, Beginn der Drehung nach rechts mit gelöster Kreuzung, Ende mit Gewicht auf RF in PP",
            "S Q Q S Q Q (2 Takte)",
            "H, H, BH, B, B of RF und H of LF, Whole of RF und IE of B LF",
            "Eine komplette Rechtsdrehung",
            "Progressive Link; Natural Promenade Turn; Four Step; Fallaway Promenade; Oversway; Five Step; Reverse Five Step; Walk auf RF in PP gedreht; jedes Closed Finish in PP gedreht; Brush Tap in PP gedreht; Promenade Link endend in PP",
            "Closed Promenade; Open Promenade; Natural Promenade Turn; Natural Promenade Turn to Natural Rock Turn; Promenade Link; Fallaway Promenade; Back Open Promenade; Chase",
        ),
        (
            "Promenade Link",
            "Kurze Verbindungsfigur aus der PP zurück in geschlossene Haltung oder fortgesetzt in PP.",
            "Anfänger",
            None,
            "LF Seite in PP, RF vor und quer in CBMP und PP, LF schließt fast an RF (ohne Gewicht)",
            "S Q Q (1 Takt)",
            "H, H, IE of B",
            "1/4 links zwischen 2 und 3",
            "Progressive Link; Natural Promenade Turn; Natural Twist Turn; Four Step; Fallaway Promenade; Chase; Oversway; Five Step; Reverse Five Step; Walk auf RF in PP gedreht; jedes Closed Finish in PP gedreht; Brush Tap in PP gedreht",
            "Walk auf LF; Progressive Side Step; Progressive Link; Four Step; Brush Tap; Rock auf LF. Endend DC: jede Reverse-Figur. Endend in PP: jede Promenadenfigur. An einer Ecke: Four Step, Brush Tap, Four Step Change, Five Step; Back Corte down new LOD; Rock auf LF",
        ),
        (
            "Four Step",
            "Vierschrittige Figur mit progressivem Wechsel und sehr vielseitigem Anschluss.",
            "Anfänger",
            None,
            "LF vor in CBMP, RF Seite und etwas zurück, LF zurück in CBMP, RF schließt an LF und etwas zurück in PP",
            "Q Q Q Q (1 Takt)",
            "H, BH, BH, BH",
            "Keine Drehung (oder 1/4 links zwischen 3 und 4)",
            "Walk auf RF; jedes Closed/Open Finish; Promenade Link; Natural Promenade Turn; Natural Rock Turn to Natural Twist Turn; Chase; Outside Swivel to Right oder Outside Swivel to Left nach Schritt 2",
            "Closed Promenade; Open Promenade; Natural Promenade Turn; Natural Promenade Turn to Natural Rock Turn; Natural Twist Turn; Fallaway Promenade; Promenade Link; Back Open Promenade; Chase",
        ),
        (
            "Brush Tap",
            "Markanter Tap-Akzent mit Brush, häufig zur Modulation des Rhythmus eingesetzt.",
            "Anfänger",
            None,
            "LF vor in CBMP, RF Seite, LF streicht zu RF (ohne Gewicht), Tap LF zur Seite (ohne Gewicht)",
            "Q Q & S (1 Takt)",
            "H, BH, F slightly off the floor, IE of B",
            "1/4 links zwischen 1 und 2 (an einer Ecke 1/8 links möglich)",
            "Walk auf RF; Promenade Link; jedes Closed/Open Finish",
            "Walk auf LF; Progressive Side Step; jede Reverse-Figur. Walk auf LF; Progressive Link; Four Step; Four Step Change; Five Step",
        ),
        (
            "Outside Swivel to Right",
            "Außenwechsel mit kräftigem Swivel nach rechts und Wechsel in PP.",
            "Fortgeschritten",
            None,
            "LF zurück in CBMP (RF in CBMP mit Druck auf OE of T of RF, ohne Gewicht, in PP), RF vor und quer in CBMP und PP, LF Seite (ohne Gewicht)",
            "S Q Q (1 Takt)",
            "BH mit Druck auf OE of T of RF, H, IE of B LF",
            "Knapp 1/8 rechts auf 1; 1/8 rechts auf 3",
            "Open Promenade; Open Reverse Turn endend zwischen Wall und DW",
            "Walk auf LF; Progressive Side Step; Progressive Link; Four Step; Brush Tap; Four Step Change; Five Step; Back Corte; Rock auf LF. Endend in PP: jede Promenadenfigur. An einer Ecke: Rock auf LF, Back Corte down new LOD, Four Step, Brush Tap, Four Step Change, Five Step",
        ),
        (
            "Outside Swivel to Left",
            "Außenwechsel mit Swivel nach links zurück in geschlossene Haltung.",
            "Fortgeschritten",
            None,
            "LF zurück in CBMP (RF wandert vor LF, ohne Gewicht), RF vor und quer in CBMP und PP, LF Seite (ohne Gewicht)",
            "S Q Q (1 Takt)",
            "BH of LF mit OE of T of RF im leichten Bodenkontakt, H, IE of B",
            "1/4 nach links",
            "Open Promenade; Open Reverse Turn Lady Outside",
            "Basic Reverse Turn; Open Reverse Turn Lady in Line; Open Reverse Turn Lady Outside; Progressive Side Step Reverse Turn; Reverse Outside Swivel; Oversway; Reverse Five Step",
        ),
        (
            "Reverse Outside Swivel",
            "Reverse-Variante des Outside Swivel mit Rückführung in die Closed Hold.",
            "Fortgeschritten",
            None,
            "LF vor in CBMP, RF Seite, LF zurück in CBMP (RF wandert vor LF), RF vor und quer in CBMP und PP, LF Seite (ohne Gewicht)",
            "Q Q S Q Q (1½ Takte)",
            "H, BH, BH of LF mit OE of T of RF im leichten Bodenkontakt, H, IE of B",
            "3/4 nach links",
            "Walk auf RF; jedes Closed/Open Finish endend DC; Promenade Link endend DC; Brush Tap; Four Step Change; Outside Swivel to Left",
            "Walk auf LF; Progressive Side Step; Progressive Link; Four Step; Brush Tap; Four Step Change",
        ),
        (
            "Fallaway Promenade",
            "Promenadenfigur mit Fallaway-Charakter, Rückwärtswiegen in PP.",
            "Fortgeschritten",
            None,
            "LF Seite in PP, RF vor und quer in CBMP und PP, LF Seite in PP, RF zurück (R-Seite führend) in Fallaway Position, LF zurück in CBMP und Fallaway Position, RF schließt an LF und etwas zurück in PP",
            "S Q Q S Q Q (2 Takte)",
            "H, H, BH, IE of BH, BH, BH",
            "3/8 rechts zwischen 1 und 4; 1/4 links zwischen 5 und 6",
            "Progressive Link; Natural Promenade Turn; Natural Twist Turn; Four Step; Oversway; Five Step; Reverse Five Step; Walk auf RF in PP gedreht; jedes Closed Finish in PP gedreht; Brush Tap in PP gedreht; Promenade Link endend in PP",
            "Closed Promenade; Open Promenade; Natural Promenade Turn; Natural Promenade Turn to Natural Rock Turn; Natural Twist Turn; Promenade Link; Back Open Promenade; Chase",
        ),
        (
            "Four Step Change",
            "Erweiterte Four-Step-Variante mit Slip auf dem vierten Schritt.",
            "Fortgeschritten",
            None,
            "LF vor in CBMP, RF Seite und etwas zurück, LF schließt an RF und etwas vor, Slip RF zurück (sehr kleiner Schritt)",
            "Q Q & S (1 Takt)",
            "H, BH, Whole F, BH",
            "1/4 links zwischen 1 und 2",
            "Walk auf RF; jedes Closed/Open Finish; Promenade Link",
            "Basic Reverse Turn; Open Reverse Turn Lady in Line; Open Reverse Turn Lady Outside; Progressive Side Step Reverse Turn; Reverse Outside Swivel; Oversway; Reverse Five Step. An einer Ecke: Walk auf LF, Progressive Link, Progressive Side Step, Four Step, Five Step",
        ),
        (
            "Back Open Promenade",
            "Rückwärtsbewegte Promenade in offener Haltung mit Wiederholungsoption.",
            "Fortgeschritten",
            None,
            "LF Seite in PP, RF vor und quer in CBMP und PP, LF Seite und etwas zurück, RF zurück in CBMP",
            "S Q Q S (1½ Takte)",
            "H, H, BH, BH",
            "1/4 rechts zwischen 2 und 3; Körperdrehung links auf 4",
            "Progressive Link; Natural Promenade Turn; Natural Twist Turn; Four Step; Fallaway Promenade; Oversway; Five Step; Reverse Five Step; Walk auf RF in PP gedreht; jedes Closed Finish in PP gedreht; Brush Tap in PP gedreht; Promenade Link endend in PP",
            "Four Step; Brush Tap; Four Step Change; Five Step; Back Corte; Rock auf LF; LF zurück down LOD in den Oversway (S S S). Schritte 3 und 4 können wiederholt werden",
        ),
        (
            "Chase",
            "Charakteristische Verfolgungsfigur mit scharfem Körperdrehmoment des Herrn auf Schritt 4.",
            "Fortgeschritten",
            None,
            "LF Seite in PP, RF vor und quer in CBMP und PP, LF Seite und etwas vor, RF vor in CBMP OP, LF zurück in CBMP, RF zur Seite und ohne Gewicht in PP",
            "S Q Q S Q Q (2 Takte)",
            "H, H, BH, BH, BH, BH dann IE of B LF",
            "3/4 rechts zwischen 2 und 6; 1/8 links zwischen 2 und 3; 7/8 rechts zwischen 3 und 6",
            "Progressive Link; Natural Promenade Turn; Natural Twist Turn; Four Step; Fallaway Promenade; Oversway; Five Step; Reverse Five Step; Walk auf RF in PP gedreht; jedes Closed Finish in PP gedreht; Brush Tap in PP gedreht; Promenade Link endend in PP",
            "Closed Promenade; Open Promenade; Natural Promenade Turn to Natural Rock Turn; Natural Twist Turn; Promenade Link; Fallaway Promenade; Back Open Promenade. An einer Ecke endend DW: jede Promenadenfigur. Nach Schritt 5: Chasse nach rechts oder LF crossed behind RF in Fallaway Position",
        ),
        (
            "Oversway",
            "Markante Schräglage mit gestrecktem freien Bein, häufig Show-Element der Choreographie.",
            "Fortgeschritten",
            None,
            "LF vor in CBMP, RF Seite und etwas zurück, LF zur Seite (Knie beugt, RF zeigt zwischen Wall und DW), L-Knie gebeugt – R-Knie schwingt nach innen, Gewichtsverlagerung zum RF in PP",
            "Q Q S S S (2 Takte)",
            "H, BH, IE of BH zur ganzen Fußfläche, ganze Sohle LF und Druck auf IE of B of RF, BH und IE of B of LF",
            "Knapp 3/4 nach links zwischen 1 und 4; Körperdrehung nach rechts auf 5",
            "Walk auf RF; jedes Closed/Open Finish endend DC; Promenade Link endend DC; Brush Tap; Four Step Change; Outside Swivel to Left",
            "Closed Promenade; Open Promenade; Natural Promenade Turn; Natural Promenade Turn to Natural Rock Turn; Natural Twist Turn; Promenade Link; Fallaway Promenade; Back Open Promenade; Chase. Nach Schritt 5 zusätzlich: LF crossed behind RF in Fallaway Position. Nach Schritt 4: Chasse to Right oder Spin to Right",
        ),
        (
            "Five Step",
            "Fünfschrittige Figur mit prägnantem Heel-Lower auf dem vierten Schritt.",
            "Fortgeschritten",
            None,
            "LF vor in CBMP, RF Seite und etwas zurück, LF zurück in CBMP, RF zurück und etwas seitlich, LF Seite (ohne Gewicht) in PP",
            "Q Q Q Q S (1½ Takte)",
            "H, BH, BH, BH, IE of B LF",
            "1/4 links zwischen 1 und 2; Körperdrehung rechts auf 5",
            "Walk auf RF; jedes Closed/Open Finish; Promenade Link; Brush Tap (ohne Drehung)",
            "Closed Promenade; Open Promenade; Natural Promenade Turn to Natural Rock Turn; Natural Twist Turn; Promenade Link; Fallaway Promenade; Back Open Promenade; Chase",
        ),
        (
            "Reverse Five Step",
            "Linksdrehende Variante des Five Step, endet in PP.",
            "Fortgeschritten",
            None,
            "LF vor in CBMP, RF Seite und etwas zurück, LF zurück in CBMP, RF zurück, LF Seite (ohne Gewicht) in PP",
            "Q Q Q Q S (1½ Takte)",
            "H, BH, BH, BH, IE of B of LF",
            "3/4 nach links; zusätzliche 1/2 Linksdrehung",
            "Walk auf RF; jedes Closed/Open Finish endend DC; Promenade Link endend DC; Brush Tap endend DC; Four Step Change; Outside Swivel to Left",
            "Closed Promenade; Open Promenade; Natural Promenade Turn to Natural Rock Turn; Natural Twist Turn; Promenade Link; Fallaway Promenade; Back Open Promenade; Chase",
        ),
        (
            "Fallaway Four Step",
            "Four-Step-Variation aus der Fallaway Position, endet im Gesicht zu DC.",
            "Fortgeschritten",
            None,
            "LF vor in CBMP, RF Seite und etwas zurück in Fallaway Position, LF zurück in CBMP und Fallaway Position, RF schließt an LF und etwas zurück in PP",
            "Q Q Q Q (1 Takt)",
            "H, BH, BH, BH",
            "1/4 links zwischen 1 und 2; keine weitere Drehung",
            "Walk auf RF; jedes Closed/Open Finish; Promenade Link; Brush Tap (ohne Drehung)",
            "Closed Promenade; Open Promenade; Natural Promenade Turn to Natural Rock Turn; Natural Twist Turn; Promenade Link; Fallaway Promenade; Back Open Promenade; Chase",
        ),
        (
            "Fallaway Reverse Turn and Slip Pivot",
            "Linksdrehung aus dem Fallaway mit einem charakteristischen Slip Pivot zum Abschluss.",
            "Fortgeschritten",
            None,
            "LF vor in CBMP, RF zurück (R-Seite führend) in Fallaway Position, LF zurück in CBMP und Fallaway, RF zurück, LF held in CBMP (Slip Pivot)",
            "Q Q Q Q (1 Takt)",
            "H, BH, BH, BHB",
            "3/4 nach links zwischen 1 und 2; 3/4 nach links zwischen 3 und 4",
            "Walk auf RF; jedes Closed/Open Finish endend DC; Promenade Link endend DC; Brush Tap; Four Step Change; Five Step; Contra Check",
            "Progressive Link; Progressive Side Step; Four Step; Four Step Change; Outside Swivel to Left",
        ),
        (
            "Reverse Pivot",
            "Schneller Pivot nach links aus dem Schrittfluss heraus, oft als Akzent.",
            "Fortgeschritten",
            None,
            "RF zurück in CBMP, kleiner Schritt LF in CBMP",
            "S (½ Takt)",
            "BHB",
            "1/8 links zwischen vorhergehendem Schritt und 1, weitere 1/8, 1/4 oder 3/8",
            "Schritte 1–3 des Basic Reverse Turn; Schritte 1–3 des Open Reverse Turn Lady in Line; Schritte 1–4 des Natural Rock Turn",
            "Endend DW: Walk auf LF, Progressive Side Step, Four Step Change, Fallaway Four Step, Brush Tap, Four Step, Five Step. Endend LOD: Walk auf LF. Endend DC: Basic Reverse Turn, Open Reverse Turn Lady in Line/Outside, Progressive Side Step Reverse Turn, Four Step, Reverse Outside Swivel, Oversway, Reverse Five Step",
        ),
        (
            "Contra Check",
            "Dramatischer Vorwärts-Check mit starker Pose und klarem Gewichtswechsel.",
            "Fortgeschritten",
            None,
            "LF vor in CBMP, Gewichtsverlagerung zu RF, LF zur Seite (ohne Gewicht) in PP",
            "S Q Q (1 Takt)",
            "H, BH, IE of B of LF",
            "Körperdrehung links auf 1; Körperdrehung rechts auf 2; 1/4 rechts zwischen 2 und 3",
            "Jedes Closed Finish; Fallaway Reverse Turn Slip Pivot; Natural Promenade Turn; Fallaway Promenade",
            "Closed Promenade; Open Promenade; Natural Promenade Turn to Natural Rock Turn; Natural Twist Turn; Promenade Link; Chase",
        ),
    ],
    "Wiener Walzer": [
        (
            "Natural Turn",
            "Drehende Vorwärtsbewegung auf drei Schritten.",
            "Anfänger",
            None,
            "Vorwärts, Seite, Schluss",
            "3",
            "F: Rechts, M: Links",
            "1/4 rechts",
        ),
        (
            "Reverse Turn",
            "Linksdrehung mit flottem Fluss und enger Haltung.",
            "Anfänger",
            None,
            "Vorwärts, Seite, Schluss",
            "3",
            "F: Links, M: Rechts",
            "1/4 links",
        ),
        (
            "Fleckerls",
            "Kleine Drehkombinationen mit frequentem Richtungswechsel.",
            "Fortgeschritten",
            None,
            "Drehung, Schritt, Schluss",
            "3",
            "F: Rechts, M: Links",
            "1/2 rechts",
        ),
        (
            "Wing",
            "Wechsel aus offener Haltung in Richtung des Partners.",
            "Fortgeschritten",
            None,
            "Vorwärts, Seite, Schluss",
            "3",
            "F: Rechts, M: Links",
            "keine",
        ),
        (
            "Hesitation",
            "Kurzer Stillstand mit betonter Pose.",
            "Fortgeschritten",
            None,
            "Schritt, Pause, Schluss",
            "3",
            "F: Rechts, M: Links",
            "keine",
        ),
    ],
    "Slowfox": [
        (
            "Natural Turn",
            "Sanfte Rechtsdrehung mit fließendem Gleiten.",
            "Anfänger",
            None,
            "Vorwärts, Seite, Schluss",
            "4",
            "F: Rechts, M: Links",
            "1/4 rechts",
        ),
        (
            "Closed Impetus",
            "Drehung in geschlossener Haltung mit einem Impuls.",
            "Fortgeschritten",
            None,
            "Seitwärts, Drehung, Schluss",
            "4",
            "F: Rechts, M: Links",
            "1/4 rechts",
        ),
        (
            "Open Impetus",
            "Ähnliche Technik wie Closed Impetus, aber aus offener Haltung.",
            "Fortgeschritten",
            None,
            "Seiten, Drehung, Schluss",
            "4",
            "F: Rechts, M: Links",
            "1/4 rechts",
        ),
        (
            "Feather Step",
            "Leistungsfähiger Schritt mit langen Linien.",
            "Fortgeschritten",
            None,
            "Vorwärts, Vorwärts, Schluss",
            "4",
            "F: Rechts, M: Links",
            "keine",
        ),
        (
            "Three Step",
            "Drei-Schritt-Folge mit elegantem Gleiten.",
            "Fortgeschritten",
            None,
            "Vorwärts, Seite, Schluss",
            "4",
            "F: Rechts, M: Links",
            "keine",
        ),
    ],
    "Quickstep": [
        (
            "Basic Step",
            "Schneller Grundschritt mit leichtem Hopser.",
            "Anfänger",
            None,
            "Vorwärts, Seite, Schluss",
            "6",
            "F: Rechts, M: Links",
            "keine",
        ),
        (
            "Quarter Turn",
            "Drehung um 90 Grad während des Grundschritts.",
            "Fortgeschritten",
            None,
            "Vorwärts, Seite, Schluss",
            "6",
            "F: Rechts, M: Links",
            "1/4 rechts",
        ),
        (
            "Lock Step",
            "Schrittfolge mit gekreuztem Standbein.",
            "Fortgeschritten",
            None,
            "Vorwärts, Vorwärts, Lock",
            "6",
            "F: Rechts, M: Links",
            "keine",
        ),
        (
            "Shoulder Glide",
            "Seitliche Bewegung mit schulterbetontem Gleiten.",
            "Fortgeschritten",
            None,
            "Seiten, Vorwärts, Schluss",
            "6",
            "F: Rechts, M: Links",
            "keine",
        ),
        (
            "Tipple Chasse",
            "Kombination aus Tipple-Step und Chasse.",
            "Fortgeschritten",
            None,
            "Vorwärts, Seite, Chasse",
            "6",
            "F: Rechts, M: Links",
            "keine",
        ),
    ],
    "Cha Cha Cha": [
        (
            "Time Step",
            "Grundfigur am Platz.",
            "Anfänger",
            None,
            "Vorwärts, Zurück, Cha Cha Cha",
            "8",
            "F: Rechts, M: Links",
            "keine",
        ),
        (
            "New York",
            "Öffnungsfigur mit Handwechsel.",
            "Anfänger",
            None,
            "Vorwärts, Seite, Cha Cha Cha",
            "8",
            "F: Rechts, M: Links",
            "keine",
        ),
        (
            "Hand to Hand",
            "Seitlicher Wechsel mit Handfassung.",
            "Fortgeschritten",
            None,
            "Seiten, Cha Cha Cha, Seite",
            "8",
            "F: Rechts, M: Links",
            "keine",
        ),
        (
            "Alemana",
            "Fließender Seitenschritt mit Drehung.",
            "Fortgeschritten",
            None,
            "Vorwärts, Drehung, Cha Cha Cha",
            "8",
            "F: Rechts, M: Links",
            "1/4 rechts",
        ),
        (
            "Cuban Break",
            "Charakteristischer Rückschritt mit Hüftwirkung.",
            "Fortgeschritten",
            None,
            "Zurück, Cha Cha Cha, Vorwärts",
            "8",
            "F: Rechts, M: Links",
            "keine",
        ),
        (
            "Underarm Turn",
            "Drehung der Dame unter erhobenem Arm des Herren.",
            "Fortgeschritten",
            None,
            "Seiten, Drehung, Cha Cha Cha",
            "8",
            "F: Rechts, M: Links",
            "1/2 rechts",
        ),
    ],
    "Rumba": [
        (
            "Basic",
            "Langsame Grundfigur mit Betonung der Hüfte.",
            "Anfänger",
            None,
            "Vorwärts, Zurück, Seite",
            "4",
            "F: Rechts, M: Links",
            "keine",
        ),
        (
            "Side Break",
            "Seitlicher Ausfallschritt mit Gewichtswechsel.",
            "Anfänger",
            None,
            "Seite, Gewicht, Schließen",
            "4",
            "F: Rechts, M: Links",
            "keine",
        ),
        (
            "Cucaracha",
            "Seitliche Hüftbewegung mit kleinen Schritten.",
            "Fortgeschritten",
            None,
            "Seite, Seite, Schließen",
            "4",
            "F: Rechts, M: Links",
            "keine",
        ),
        (
            "Spot Turn",
            "Drehung auf der Stelle, meist der Dame.",
            "Fortgeschritten",
            None,
            "Drehung, Schritt, Schließen",
            "4",
            "F: Rechts, M: Links",
            "1/4 rechts",
        ),
        (
            "Alemana",
            "Fließende Seitwärtsbewegung mit Drehpassage.",
            "Fortgeschritten",
            None,
            "Seite, Drehung, Schließen",
            "4",
            "F: Rechts, M: Links",
            "keine",
        ),
    ],
    "Samba": [
        (
            "Basic",
            "Grundschritt mit typischem Samba-Rhythmus.",
            "Anfänger",
            None,
            "Vorwärts, Rückwärts, Abschluss",
            "4",
            "F: Rechts, M: Links",
            "keine",
        ),
        (
            "Botafogo",
            "Schräg vorwärts mit Gewichtsverlagerung nach außen.",
            "Fortgeschritten",
            None,
            "Vorwärts, Seite, Schluss",
            "4",
            "F: Rechts, M: Links",
            "keine",
        ),
        (
            "Volta",
            "Runder Schritt mit Drehung in Laufrichtung.",
            "Fortgeschritten",
            None,
            "Vorwärts, Seite, Schluss",
            "4",
            "F: Rechts, M: Links",
            "keine",
        ),
        (
            "Whisk",
            "Seitlicher Schritt mit abwehrender Hüftbewegung.",
            "Fortgeschritten",
            None,
            "Seite, Rück, Schluss",
            "4",
            "F: Rechts, M: Links",
            "keine",
        ),
        (
            "Samba Roll",
            "Gleiten in einer sanften Rollbewegung.",
            "Fortgeschritten",
            None,
            "Vorwärts, Seite, Schluss",
            "4",
            "F: Rechts, M: Links",
            "keine",
        ),
    ],
    "Jive": [
        (
            "Basic",
            "Schneller Grundschritt mit Kick im Rhythmus.",
            "Anfänger",
            None,
            "Vorwärts, Zurück, Kick",
            "6",
            "F: Rechts, M: Links",
            "keine",
        ),
        (
            "Link",
            "Wechsel aus dem Grundschritt mit seitlichem Zurücksetzen.",
            "Anfänger",
            None,
            "Zurück, Seite, Kick",
            "6",
            "F: Rechts, M: Links",
            "keine",
        ),
        (
            "Heel Jerk",
            "Kraftvoller Kick mit geführtem Rückschritt.",
            "Fortgeschritten",
            None,
            "Vorwärts, Kick, Zurück",
            "6",
            "F: Rechts, M: Links",
            "keine",
        ),
        (
            "Circle",
            "Rundlauf mit enger, schneller Rotation.",
            "Fortgeschritten",
            None,
            "Vorwärts, Seite, Kick",
            "6",
            "F: Rechts, M: Links",
            "1/2 rechts",
        ),
        (
            "Fallaway",
            "Zurückfallen aus dem Paar mit anschließendem Blickwechsel.",
            "Fortgeschritten",
            None,
            "Zurück, Seite, Kick",
            "6",
            "F: Rechts, M: Links",
            "keine",
        ),
    ],
    "Paso Doble": [
        (
            "Basic",
            "Starker Grundschritt im spanischen Charakter.",
            "Anfänger",
            None,
            "Vorwärts, Seite, Schluss",
            "4",
            "F: Rechts, M: Links",
            "keine",
        ),
        (
            "Chasse",
            "Seitlicher Schritt mit geschlossenen Füßen.",
            "Anfänger",
            None,
            "Seite, Seite, Schluss",
            "4",
            "F: Rechts, M: Links",
            "keine",
        ),
        (
            "Promenade",
            "Vorwärtsbewegung in offener Haltung.",
            "Fortgeschritten",
            None,
            "Vorwärts, Seite, Schluss",
            "4",
            "F: Rechts, M: Links",
            "keine",
        ),
        (
            "Spanish Line",
            "Haltung mit geschlossenen Armen und starker Pose.",
            "Fortgeschritten",
            None,
            "Vorwärts, Seite, Schluss",
            "4",
            "F: Rechts, M: Links",
            "keine",
        ),
        (
            "Fan",
            "Öffnende Bewegung mit seitlicher Damenführung.",
            "Fortgeschritten",
            None,
            "Seite, Drehen, Schluss",
            "4",
            "F: Rechts, M: Links",
            "keine",
        ),
    ],
    "Discofox": [
        (
            "Grundschritt",
            "Einfacher Discofox-Grundschritt.",
            "Anfänger",
            None,
            "Vorwärts, Zurück, Drehung",
            "6",
            "F: Rechts, M: Links",
            "1/4 rechts",
        ),
        (
            "Damensolodrehung",
            "Drehung der Dame unter erhobenem Arm.",
            "Anfänger",
            None,
            "Drehung, Schritt, Schließen",
            "6",
            "F: Rechts, M: Links",
            "1/2 rechts",
        ),
        (
            "Herrensolodrehung",
            "Drehung des Herrn unter erhobenem Arm.",
            "Fortgeschritten",
            None,
            "Drehung, Schritt, Schließen",
            "6",
            "F: Links, M: Rechts",
            "1/2 links",
        ),
        (
            "Underarm Turn",
            "Drehung der Dame unter dem Arm des Führenden.",
            "Anfänger",
            None,
            "Seiten, Drehung, Schließen",
            "6",
            "F: Rechts, M: Links",
            "1/2 rechts",
        ),
        (
            "Step Turn",
            "Kombination aus Schritt und Drehung.",
            "Fortgeschritten",
            None,
            "Vorwärts, Seite, Schließen",
            "6",
            "F: Rechts, M: Links",
            "1/4 rechts",
        ),
    ],
}

SAMPLE_SEQUENCES = {
    "Discofox": [
        ("Standard-Folge", "Grundschritt, Damensolodrehung, Grundschritt", "Eine klassische Einsteigerfolge."),
    ],
    "Cha Cha Cha": [
        ("Anfängerfolge", "Time Step, New York, Time Step", "Folge für Einsteiger."),
    ],
}


def seed():
    init_db()
    conn = get_connection()
    cur = conn.cursor()

    for name in COURSES:
        cur.execute("INSERT OR IGNORE INTO courses (name) VALUES (?)", (name,))
    for name in DANCES:
        cur.execute("INSERT OR IGNORE INTO dances (name) VALUES (?)", (name,))
    conn.commit()

    cur.execute("SELECT id, name FROM courses")
    course_ids = {row["name"]: row["id"] for row in cur.fetchall()}
    cur.execute("SELECT id, name FROM dances")
    dance_ids = {row["name"]: row["id"] for row in cur.fetchall()}

    for u in DEFAULT_USERS:
        cur.execute(
            "INSERT OR IGNORE INTO users (username, password_hash, role, course_id) VALUES (?, ?, ?, ?)",
            (
                u["username"],
                generate_password_hash(u["password"]),
                u["role"],
                course_ids[u["course"]],
            ),
        )

    for course_name, course_id in course_ids.items():
        for dance_name, figures in SAMPLE_FIGURES.items():
            dance_id = dance_ids[dance_name]
            for fig in figures:
                cur.execute(
                    "SELECT id FROM figures WHERE course_id=? AND dance_id=? AND name=?",
                    (course_id, dance_id, fig[0]),
                )
                if cur.fetchone():
                    continue
                precedes = fig[8] if len(fig) > 8 else None
                follows = fig[9] if len(fig) > 9 else None
                cur.execute(
                    "INSERT INTO figures (course_id, dance_id, name, description, difficulty, video_url, steps, count_steps, footwork, amount_of_turn, precedes, follows) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)",
                    (
                        course_id,
                        dance_id,
                        fig[0],
                        fig[1],
                        fig[2],
                        fig[3],
                        fig[4],
                        fig[5],
                        fig[6],
                        fig[7],
                        precedes,
                        follows,
                    ),
                )
        for dance_name, sequences in SAMPLE_SEQUENCES.items():
            dance_id = dance_ids[dance_name]
            for seq in sequences:
                cur.execute(
                    "SELECT id FROM sequences WHERE course_id=? AND dance_id=? AND name=?",
                    (course_id, dance_id, seq[0]),
                )
                if cur.fetchone():
                    continue
                cur.execute(
                    "INSERT INTO sequences (course_id, dance_id, name, figures, description, visible) VALUES (?,?,?,?,?,?)",
                    (course_id, dance_id, seq[0], seq[1], seq[2], 1),
                )

    conn.commit()
    conn.close()
    print("Datenbank initialisiert und Basisdaten geladen.")


if __name__ == "__main__":
    seed()
